### ISSUE TITLE
Chinese characters support

### ISSUE THREAD

**Issue by koapower** [myusername4573/SoulMeter#1]
Hello, thanks for the really nice tool!
There is a small problem that Chinese characters are not displayed properly.
For instance, please check the image file attached.
![06072021-1](https://user-images.githubusercontent.com/68468524/121002761-a5dbd900-c7c7-11eb-9f32-4fdd68b85b31.png)
Chinese characters are displayed as '?'.

**Comment by myusername4573** [comment]
ok I'll fix it later

**Comment by myusername4573** [comment]
https://github.com/myusername4573/SoulMeter/releases/tag/1.0.5.5
