### ISSUE TITLE
WinDivert cleanup

### ISSUE THREAD

**Issue by H1X4Dev** [myusername4573/SoulMeter#2]
Currently after you first run the application, it will install `WinDivert64.sys` that will persist in the system until uninstalled manually (can check using `driverquery /v` for that).

It would be a good idea if you have included an option to uninstall `WinDivert64.sys` or at least clean up after user exits SoulMeter.

At the moment, you have to download the [WinDivert](https://reqrypt.org/windivert.html) package manually and execxute `windivertctl.exe uninstall` as administrator to uninstall it.

Please cleanup after exiting the SoulMeter. You can check how its done here:
https://github.com/basil00/Divert/blob/134dd37bd0a87d3d236214e42edc1867b8911c6f/examples/windivertctl/windivertctl.c#L333

**Comment by myusername4573** [comment]
`windivertctl.exe uninstall` will kill other programs that already using windivert like `Cloudflare WARP` 
https://i.imgur.com/h8R5osK.png
So i can't automatically kill windivert

Also, you only need to reboot for removing Windivert
https://reqrypt.org/windivert-faq.html#q10

But I will add something like `[Use this only if you can't delete windivert file...bat] ` later

**Comment by H1X4Dev** [comment]
Having a bat file to remove it would be very helpful 👍

**Comment by gnidnE** [comment]
Reposting a solution from the discord you can get [here](https://cdn.discordapp.com/attachments/855194849955414026/856426255314714624/Uninstall_WinDivert.zip).

@H1X4Dev

**Comment by myusername4573** [comment]
Solved at 1.0.5.9
https://github.com/myusername4573/SoulMeter/releases/tag/1.0.5.9
